[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.17.1"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
